import {
  Activity,
  AlarmClock,
  ArrowLeftRight,
  Banknote,
  Bell,
  BellRing,
  BookOpen,
  Bot,
  Briefcase,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarOff,
  CalendarRange,
  ChartLine,
  ChartNoAxesColumn,
  Check,
  ChevronLeft,
  ChevronRight,
  ClipboardCheck,
  Code2,
  Cpu,
  CreditCard,
  Facebook,
  FileBarChart,
  FileCheck,
  FilePen,
  Files,
  FileText,
  FlaskConical,
  Github,
  Globe,
  GraduationCap,
  Heart,
  History,
  IdCard,
  Image,
  Images,
  Instagram,
  KeyRound,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Lightbulb,
  Link,
  ListTodo,
  Lock,
  LogIn,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  MessageSquare,
  Monitor,
  Network,
  PenTool,
  Play,
  QrCode,
  Receipt,
  RotateCcw,
  Rocket,
  Radio,
  School,
  ScrollText,
  Search,
  Send,
  ServerCog,
  Settings,
  Shield,
  Siren,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  SquarePen,
  SunMoon,
  TrendingUp,
  Trophy,
  UserCog,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  Video,
  Wallet,
  Webhook,
  X,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

/**
 * Single source of truth for every icon on the site.
 * Data files reference icons by name; nothing renders a raw or hand-written icon.
 */
const iconRegistry = {
  activity: Activity,
  'alarm-clock': AlarmClock,
  'arrow-left-right': ArrowLeftRight,
  banknote: Banknote,
  bell: Bell,
  'bell-ring': BellRing,
  'book-open': BookOpen,
  bot: Bot,
  briefcase: Briefcase,
  'calendar-check': CalendarCheck,
  'calendar-clock': CalendarClock,
  'calendar-days': CalendarDays,
  'calendar-off': CalendarOff,
  'calendar-range': CalendarRange,
  'chart-line': ChartLine,
  'chart-no-axes-column': ChartNoAxesColumn,
  check: Check,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'clipboard-check': ClipboardCheck,
  'code-2': Code2,
  cpu: Cpu,
  'credit-card': CreditCard,
  facebook: Facebook,
  'file-bar-chart': FileBarChart,
  'file-check': FileCheck,
  'file-pen': FilePen,
  'file-text': FileText,
  files: Files,
  'flask-conical': FlaskConical,
  globe: Globe,
  'graduation-cap': GraduationCap,
  github: Github,
  heart: Heart,
  history: History,
  'id-card': IdCard,
  image: Image,
  images: Images,
  instagram: Instagram,
  'key-round': KeyRound,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  'layout-template': LayoutTemplate,
  lightbulb: Lightbulb,
  link: Link,
  'list-todo': ListTodo,
  lock: Lock,
  'log-in': LogIn,
  mail: Mail,
  map: Map,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  monitor: Monitor,
  network: Network,
  'pen-tool': PenTool,
  play: Play,
  'qr-code': QrCode,
  receipt: Receipt,
  'rotate-ccw': RotateCcw,
  rocket: Rocket,
  radio: Radio,
  school: School,
  'scroll-text': ScrollText,
  search: Search,
  send: Send,
  'server-cog': ServerCog,
  settings: Settings,
  shield: Shield,
  siren: Siren,
  'sliders-horizontal': SlidersHorizontal,
  smartphone: Smartphone,
  sparkles: Sparkles,
  'square-pen': SquarePen,
  'sun-moon': SunMoon,
  'trending-up': TrendingUp,
  trophy: Trophy,
  'user-cog': UserCog,
  'user-plus': UserPlus,
  'user-round': UserRound,
  users: Users,
  'users-round': UsersRound,
  video: Video,
  wallet: Wallet,
  webhook: Webhook,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;

type IconProps = Omit<LucideProps, 'ref'> & { name: IconName };

export function Icon({ name, ...props }: IconProps) {
  const Component = iconRegistry[name];
  // Kontrak: semua ikon dekoratif; pemakai yang bermakna wajib punya aria-label sendiri.
  return <Component aria-hidden focusable="false" {...props} />;
}